#!/usr/bin/env python3
"""Generate a read-only MCP server package for a built ecosystem.

Emits three files into ``<build>/mcp/``:

  * ``server.py``          -- a byte-for-byte copy of scripts/mcp_server_template.py
  * ``mcp_manifest.json``  -- ecosystem-specific knowledge (tables, lineage,
                              controls, DQ rules, resources, limits)
  * ``README.md``          -- a connection guide for Claude Code / Desktop / any
                              stdio MCP host

It also writes a clean, deterministic copy of the spec to
``<build>/ecosystem_spec.json`` so the ``ecosystem://spec`` resource travels with
the package (relative path, relocatable, no absolute paths in the manifest).

The server template and manifest are stdlib-only and never touch the network.
Naming (logical -> physical), layer parsing, and FK extraction reuse
``build_sqlite_ecosystem`` so they are identical to what the engine built.

Determinism is a contract: the three emitted files are byte-identical across
runs, machines, and PYTHONHASHSEED values (no timestamps, sorted JSON keys,
explicit ``\\n`` newlines, only package-relative paths).

Usage:
  python scripts/generate_mcp_server.py <spec.json> --build <dir> \\
      [--db <path>] [--name <server-name>] [--force] [--quiet]

Exit codes: 0 success, 1 generation failure, 2 usage error.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
from pathlib import Path
from typing import Any

# Same-directory import: scripts can be invoked from anywhere.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_sqlite_ecosystem import (  # noqa: E402  (after sys.path tweak)
    ENGINE_VERSION,
    SpecError,
    TableSpec,
    load_spec,
    physical_name,
)

TEMPLATE = Path(__file__).resolve().parent / "mcp_server_template.py"

DISCLAIMER = (
    "All data is synthetic and fictional. It was generated by the "
    "agent-skill-enterprise-data-ecosystems engine and must not be treated as "
    "real organizational data or real PII."
)

LIMITS = {
    "query_default_rows": 200,
    "query_max_rows": 1000,
    "sample_max_rows": 100,
    "response_max_bytes": 1_000_000,
    "query_timeout_seconds": 5,
}

# Candidate documentation resources, relative to the build directory (the mcp/
# directory's parent). README lives in the mcp/ directory itself.
DOC_RESOURCES = [
    ("ecosystem://spec", "ecosystem_spec.json", "application/json",
     "The ecosystem spec used for this build."),
    ("ecosystem://docs/build-summary", "build_summary.json", "application/json",
     "Per-table row counts and build summary."),
    ("ecosystem://docs/validation-report", "validation_report.md", "text/markdown",
     "Strict validation report for the build."),
    ("ecosystem://docs/profile", "profile.md", "text/markdown",
     "Column/table profile of the database."),
    ("ecosystem://docs/schema-catalog", "schema_catalog.md", "text/markdown",
     "Human-readable schema catalog."),
]


def log(message: str, quiet: bool) -> None:
    if not quiet:
        print(message)


# ---------------------------------------------------------------------------
# Spec -> manifest helpers
# ---------------------------------------------------------------------------


def build_table_records(tables: list[TableSpec]) -> list[dict[str, Any]]:
    """Manifest table entries, sorted by logical key. Naming and FK extraction
    come straight from TableSpec so they match the built database exactly."""
    records = []
    for tbl in tables:
        fk_by_col = {col: ref for col, ref in tbl.fk_refs()}
        columns = []
        for col in tbl.columns:
            columns.append({
                "name": col.get("name"),
                "type": col.get("type", "string"),
                "nullable": col.get("nullable", True) is not False,
                "sensitivity": col.get("sensitivity"),
                "fk_target": fk_by_col.get(col.get("name")),
            })
        records.append({
            "key": tbl.key,
            "physical": tbl.physical,
            "layer": tbl.layer,
            "source": tbl.source,
            "source_system": tbl.source_system,
            "purpose": tbl.purpose,
            "grain": tbl.grain,
            "primary_key": list(tbl.primary_key),
            "natural_key": list(tbl.natural_key),
            "traits": list(tbl.raw.get("traits", [])),
            "columns": columns,
        })
    records.sort(key=lambda record: record["key"])
    return records


def _token_to_key(tables: list[TableSpec]) -> dict[str, str]:
    """Map every recognizable table token (logical key and physical name) to its
    canonical logical key."""
    mapping: dict[str, str] = {}
    for tbl in tables:
        mapping[tbl.key] = tbl.key
        mapping[tbl.key.lower()] = tbl.key
        mapping[tbl.physical] = tbl.key
        mapping[tbl.physical.lower()] = tbl.key
    return mapping


def _token_regex(tables: list[TableSpec]) -> "re.Pattern[str]":
    """Word-boundary alternation over every known table token, longest first so
    physical names never partially shadow logical keys."""
    tokens = set()
    for tbl in tables:
        tokens.add(tbl.key)
        tokens.add(tbl.physical)
    ordered = sorted(tokens, key=len, reverse=True)
    if not ordered:
        return re.compile(r"(?!x)x")  # matches nothing
    alternation = "|".join(re.escape(token) for token in ordered)
    return re.compile(r"\b(" + alternation + r")\b", re.IGNORECASE)


_WRITE_TARGET_PATTERNS = [
    re.compile(r"insert\s+(?:or\s+\w+\s+)?into\s+[\"'\[]?([A-Za-z_][\w.]*)", re.IGNORECASE),
    re.compile(r"create\s+(?:temp(?:orary)?\s+)?(?:view|table)\s+(?:if\s+not\s+exists\s+)?"
               r"[\"'\[]?([A-Za-z_][\w.]*)", re.IGNORECASE),
    re.compile(r"replace\s+into\s+[\"'\[]?([A-Za-z_][\w.]*)", re.IGNORECASE),
    re.compile(r"update\s+[\"'\[]?([A-Za-z_][\w.]*)", re.IGNORECASE),
]


def _derivation_sql(deriv: dict[str, Any]) -> str:
    sql = deriv.get("sql", "")
    if isinstance(sql, list):
        sql = "\n".join(str(part) for part in sql)
    return str(sql)


def extract_lineage(spec: dict[str, Any], tables: list[TableSpec]) -> list[dict[str, Any]]:
    """Build lineage edges from spec derivations (write target downstream, every
    referenced table upstream) plus dataflows (consecutive recognized tables in
    the declared sequence). Over-approximates slightly on pathological names by
    design; sorted and de-duplicated for determinism."""
    token_to_key = _token_to_key(tables)
    token_regex = _token_regex(tables)
    edges: set[tuple[str, str, str, str]] = set()

    def resolve(token: str) -> str | None:
        return token_to_key.get(token) or token_to_key.get(token.lower())

    # --- derivations ---
    for index, deriv in enumerate(spec.get("derivations", [])):
        name = deriv.get("name", f"derivation_{index}")
        sql = _derivation_sql(deriv)
        referenced = {resolve(m.group(1)) for m in token_regex.finditer(sql)}
        referenced.discard(None)
        downstream = set()
        for pattern in _WRITE_TARGET_PATTERNS:
            for match in pattern.finditer(sql):
                key = resolve(match.group(1))
                if key is not None:
                    downstream.add(key)
        upstream = referenced - downstream
        for target in downstream:
            for source in upstream:
                if source != target:
                    edges.add((source, target, name, "derivation"))

    # --- dataflows ---
    for index, flow in enumerate(spec.get("dataflows", [])):
        name = flow.get("name", f"dataflow_{index}")
        sequence = flow.get("sequence") or flow.get("path") or ""
        chain: list[str] = []
        for match in token_regex.finditer(str(sequence)):
            key = resolve(match.group(1))
            if key is not None and (not chain or chain[-1] != key):
                chain.append(key)
        # Explicit source/target fields, if a spec ever declares them.
        for field_from, field_to in (("source", "target"), ("from", "to")):
            src = flow.get(field_from)
            dst = flow.get(field_to)
            if src and dst:
                src_key = resolve(str(src))
                dst_key = resolve(str(dst))
                if src_key and dst_key and src_key != dst_key:
                    edges.add((src_key, dst_key, name, "dataflow"))
        for first, second in zip(chain, chain[1:]):
            if first != second:
                edges.add((first, second, name, "dataflow"))

    ordered = sorted(edges, key=lambda edge: (edge[0], edge[1], edge[2]))
    return [{"from": f, "to": t, "via": v, "kind": k} for (f, t, v, k) in ordered]


def build_resources(build_dir: Path, mcp_dir: Path) -> list[dict[str, Any]]:
    """List documentation resources that exist on disk at generation time,
    sorted by uri. Paths are stored relative to the manifest directory."""
    resources = []
    for uri, filename, mimetype, description in DOC_RESOURCES:
        target = build_dir / filename
        if target.exists():
            rel = Path(os.path.relpath(target, mcp_dir)).as_posix()
            resources.append({"uri": uri, "path": rel, "mimeType": mimetype,
                              "description": description})
    # DDL files under <build>/sqlite/.
    sql_dir = build_dir / "sqlite"
    if sql_dir.is_dir():
        for sql_file in sorted(sql_dir.glob("*.sql")):
            basename = sql_file.stem
            rel = Path(os.path.relpath(sql_file, mcp_dir)).as_posix()
            resources.append({"uri": f"ecosystem://ddl/{basename}", "path": rel,
                              "mimeType": "application/sql",
                              "description": f"DDL artifact {sql_file.name}."})
    # The generated README always ships in the mcp/ directory itself.
    resources.append({"uri": "ecosystem://docs/server-readme", "path": "README.md",
                      "mimeType": "text/markdown",
                      "description": "This server's connection guide."})
    resources.sort(key=lambda resource: resource["uri"])
    return resources


def build_manifest(spec: dict[str, Any], tables: list[TableSpec], server_name: str,
                   db_rel: str, resources: list[dict[str, Any]]) -> dict[str, Any]:
    org = spec.get("organization", {})
    time_block = spec.get("time", {})
    return {
        "manifest_version": 1,
        "server_name": server_name,
        "engine_version": ENGINE_VERSION,
        "database": db_rel,
        "disclaimer": DISCLAIMER,
        "organization": {
            "name": org.get("name"),
            "archetype": org.get("archetype"),
            "industry": org.get("industry"),
            "currency": org.get("currency"),
        },
        "time": {
            "start_date": time_block.get("start_date"),
            "end_date": time_block.get("end_date"),
            "as_of_date": time_block.get("as_of_date") or time_block.get("end_date"),
        },
        "tables": build_table_records(tables),
        "lineage": extract_lineage(spec, tables),
        "controls": spec.get("controls", []),
        "dq_rules": spec.get("dq_rules", []),
        "required_views": (spec.get("validation", {}) or {}).get("required_views", []),
        "resources": resources,
        "limits": dict(LIMITS),
    }


# ---------------------------------------------------------------------------
# README
# ---------------------------------------------------------------------------

PLACEHOLDER_PATH = "/absolute/path/to/this/directory/server.py"

TOOL_SUMMARY = [
    ("get_ecosystem_overview", "organization, time horizon, scale, table/row/imperfection counts"),
    ("list_tables", "tables with layer, purpose, grain, source, and live row counts"),
    ("describe_table", "full column-level schema for one table"),
    ("sample_rows", "first rows of a table in deterministic order"),
    ("query", "a single read-only SELECT/WITH query (row + 1 MB caps, 5 s timeout)"),
    ("get_lineage", "transitive upstream/downstream lineage for a table"),
    ("list_imperfections", "intentional data-quality defects, totals and examples"),
    ("get_table_profile", "live null %, distinct count, and min/max per column"),
    ("list_controls", "declared reconciliation/business controls"),
    ("list_dq_rules", "declared data-quality rules"),
    ("get_build_info", "build provenance, db size, SQLite version"),
]


def render_readme(server_name: str, manifest: dict[str, Any]) -> str:
    org = manifest["organization"]
    org_name = org.get("name", "this organization")
    table_count = len(manifest["tables"])
    config_json = json.dumps(
        {"mcpServers": {server_name: {"command": "python",
                                      "args": [PLACEHOLDER_PATH]}}},
        indent=2)

    lines: list[str] = []
    lines.append(f"# {server_name}")
    lines.append("")
    lines.append(f"A read-only [MCP](https://modelcontextprotocol.io) server over the synthetic "
                 f"**{org_name}** data ecosystem ({table_count} tables across the warehouse stack).")
    lines.append("")
    lines.append(f"> {DISCLAIMER}")
    lines.append("")
    lines.append("## Requirements")
    lines.append("")
    lines.append("- Python 3.9 or newer. Nothing else — the server is standard-library only, with "
                 "no third-party packages and no network access.")
    lines.append("")
    lines.append("## Connect")
    lines.append("")
    lines.append("Substitute the real absolute path to `server.py` in this directory for "
                 f"`{PLACEHOLDER_PATH}` in every block below.")
    lines.append("")
    lines.append("### Claude Code")
    lines.append("")
    lines.append("```sh")
    lines.append(f"claude mcp add {server_name} -- python {PLACEHOLDER_PATH}")
    lines.append("```")
    lines.append("")
    lines.append("Or add it to a project-scoped `.mcp.json`:")
    lines.append("")
    lines.append("```json")
    lines.append(config_json)
    lines.append("```")
    lines.append("")
    lines.append("### Claude Desktop")
    lines.append("")
    lines.append("Add the same `mcpServers` block to `claude_desktop_config.json`. On Windows, "
                 "write paths with forward slashes or doubled backslashes "
                 "(`C:/Users/.../server.py` or `C:\\\\Users\\\\...\\\\server.py`).")
    lines.append("")
    lines.append("```json")
    lines.append(config_json)
    lines.append("```")
    lines.append("")
    lines.append("### Any stdio MCP host")
    lines.append("")
    lines.append("Run `python server.py` with this directory as the working directory. The server "
                 "speaks newline-delimited JSON-RPC 2.0 over stdio (stdout is protocol bytes only; "
                 "logs go to stderr with `--verbose`).")
    lines.append("")
    lines.append("## Tools")
    lines.append("")
    for name, summary in TOOL_SUMMARY:
        lines.append(f"- `{name}` — {summary}")
    lines.append("")
    lines.append("## Resources")
    lines.append("")
    lines.append("Documentation artifacts are exposed under the `ecosystem://` URI scheme "
                 "(only those present on disk are listed):")
    lines.append("")
    for resource in manifest["resources"]:
        lines.append(f"- `{resource['uri']}` — {resource.get('description', '')}")
    lines.append("")
    lines.append("Two prompts are provided: `tour-this-ecosystem` and `investigate-imperfections`.")
    lines.append("")
    lines.append("## Limits")
    lines.append("")
    lines.append("| Limit | Value |")
    lines.append("| --- | --- |")
    limits = manifest["limits"]
    lines.append(f"| Default query rows | {limits['query_default_rows']} |")
    lines.append(f"| Max query rows | {limits['query_max_rows']} |")
    lines.append(f"| Max sample rows | {limits['sample_max_rows']} |")
    lines.append(f"| Max response bytes | {limits['response_max_bytes']:,} |")
    lines.append(f"| Query timeout (seconds) | {limits['query_timeout_seconds']} |")
    lines.append("")
    lines.append("Every query runs read-only: a `mode=ro` connection, a deny-by-default SQLite "
                 "authorizer, single-statement SELECT/WITH vetting, the caps above, and a "
                 "wall-clock timeout. There are no write tools.")
    lines.append("")
    lines.append("## Relocating and regenerating")
    lines.append("")
    lines.append("- **Relocating:** the manifest references the database and documentation by "
                 "relative path. Move the `mcp/` directory together with its parent build "
                 "directory (the `.db`, `sqlite/`, and docs) and everything keeps working. Use "
                 "`--db` to point at a database elsewhere.")
    lines.append("- **Regenerating:** rerun `python scripts/generate_mcp_server.py <spec> "
                 "--build <dir> --force` after every rebuild — row counts, the imperfection log, "
                 "and the resource list change with each build.")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Database resolution
# ---------------------------------------------------------------------------


def resolve_database(spec: dict[str, Any], build_dir: Path, db_arg: Path | None) -> Path:
    if db_arg is not None:
        db_path = db_arg
    else:
        org_name = spec.get("organization", {}).get("name", "ecosystem")
        default_db = build_dir / (physical_name(org_name) + ".db")
        if default_db.exists():
            db_path = default_db
        else:
            db_files = sorted(build_dir.glob("*.db"))
            if len(db_files) == 1:
                db_path = db_files[0]
            elif not db_files:
                raise SpecError(f"no .db file found in {build_dir}; build the ecosystem first "
                                "or pass --db.")
            else:
                raise SpecError(f"multiple .db files in {build_dir}: "
                                f"{[f.name for f in db_files]}; disambiguate with --db.")
    if not db_path.exists():
        raise SpecError(f"database not found: {db_path}")
    try:
        conn = sqlite3.connect(f"file:{db_path.as_posix()}?mode=ro", uri=True)
        conn.execute("select 1")
        conn.close()
    except sqlite3.Error as exc:
        raise SpecError(f"cannot open database read-only: {db_path}: {exc}")
    return db_path


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def generate(spec_path: Path, build_dir: Path, db_arg: Path | None, name_arg: str | None,
             force: bool, quiet: bool) -> Path:
    spec = load_spec(spec_path)
    org_name = spec.get("organization", {}).get("name", "ecosystem")
    tables = [TableSpec(raw, i, spec) for i, raw in enumerate(spec.get("tables", []))]
    if not tables:
        raise SpecError("spec has no tables.")

    db_path = resolve_database(spec, build_dir, db_arg)
    server_name = name_arg or (physical_name(org_name).replace("_", "-") + "-data-ecosystem")

    mcp_dir = build_dir / "mcp"
    emitted = [mcp_dir / "server.py", mcp_dir / "mcp_manifest.json", mcp_dir / "README.md"]
    if mcp_dir.exists() and any(path.exists() for path in emitted) and not force:
        raise SpecError(f"{mcp_dir} already contains a generated server. Pass --force to "
                        "overwrite (regeneration is the expected workflow after a rebuild).")
    mcp_dir.mkdir(parents=True, exist_ok=True)

    # Write a clean, deterministic spec copy into the build directory so the
    # ecosystem://spec resource is BOM-free, note-stripped, and relocatable.
    spec_copy = build_dir / "ecosystem_spec.json"
    if not (spec_copy.exists() and spec_copy.resolve() == spec_path.resolve()):
        with spec_copy.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(json.dumps(spec, indent=2, sort_keys=True))
            handle.write("\n")

    db_rel = Path(os.path.relpath(db_path, mcp_dir)).as_posix()
    resources = build_resources(build_dir, mcp_dir)
    manifest = build_manifest(spec, tables, server_name, db_rel, resources)

    # server.py: byte-for-byte copy of the template.
    template_bytes = TEMPLATE.read_bytes()
    (mcp_dir / "server.py").write_bytes(template_bytes)

    # mcp_manifest.json: sorted keys, explicit newline.
    with (mcp_dir / "mcp_manifest.json").open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(json.dumps(manifest, indent=2, sort_keys=True))
        handle.write("\n")

    # README.md.
    with (mcp_dir / "README.md").open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(render_readme(server_name, manifest))

    log(f"MCP server package written to {mcp_dir}", quiet)
    log(f"  server.py        ({len(template_bytes):,} bytes, copied verbatim)", quiet)
    log(f"  mcp_manifest.json ({len(manifest['tables'])} tables, "
        f"{len(manifest['lineage'])} lineage edges, {len(resources)} resources)", quiet)
    log(f"  README.md", quiet)
    log(f"Connect with: claude mcp add {server_name} -- python "
        f"{(mcp_dir / 'server.py')}", quiet)
    return mcp_dir


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("spec", type=Path, help="Path to the ecosystem spec JSON.")
    parser.add_argument("--build", type=Path, required=True,
                        help="Build output directory (emits <build>/mcp/).")
    parser.add_argument("--db", type=Path, default=None,
                        help="Database path (default: <build>/<org>.db or the sole *.db).")
    parser.add_argument("--name", default=None, help="Server name (default derived from the org).")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing mcp/ package.")
    parser.add_argument("--quiet", action="store_true", help="Suppress progress output.")
    args = parser.parse_args(argv)

    if not args.spec.exists():
        print(f"error: spec file not found: {args.spec}", file=sys.stderr)
        return 2
    if not args.build.exists():
        print(f"error: build directory not found: {args.build}", file=sys.stderr)
        return 2
    if not TEMPLATE.exists():
        print(f"error: server template missing: {TEMPLATE}", file=sys.stderr)
        return 2
    try:
        generate(args.spec, args.build, args.db, args.name, args.force, args.quiet)
        return 0
    except SpecError as exc:
        print(f"GENERATION ERROR: {exc}", file=sys.stderr)
        return 1
    except sqlite3.Error as exc:
        print(f"DATABASE ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
